# Generated by Django 2.2.17 on 2023-10-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200403_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_campus_ambassador',
            field=models.BooleanField(default=False),
        ),
    ]
