# Generated by Django 2.2.17 on 2023-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_profile_is_campus_ambassador'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ca_score',
            field=models.IntegerField(default=0),
        ),
    ]
