# Generated by Django 2.2.17 on 2024-02-11 13:33

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_profile_ca_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='registration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 11, 19, 3, 9, 272033)),
        ),
        migrations.AlterField(
            model_name='team',
            name='access_code',
            field=models.CharField(default=uuid.UUID('18685dcc-c8e2-11ee-a479-b632e7e83fcf'), max_length=100, unique=True),
        ),
    ]
