# Generated by Django 2.2.17 on 2024-02-11 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20240211_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='access_code',
            field=models.CharField(default=uuid.UUID('454e344c-c8e2-11ee-8686-b632e7e83fcf'), max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
