# Generated by Django 2.2.17 on 2023-10-07 17:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('problem_statement', models.TextField()),
                ('round_number', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('training_points', models.TextField(blank=True, null=True)),
                ('testing_points', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('credits', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lives', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_function', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('credits', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arithmetica.RoundInfo')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arithmetica.UserInfo')),
            ],
            options={
                'unique_together': {('user_info', 'round')},
            },
        ),
    ]
