# Generated by Django 2.2.17 on 2023-10-02 07:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('problem_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lives', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('submitted_function', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('credits', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arithmetica.RoundInfo')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arithmetica.UserInfo')),
            ],
            options={
                'unique_together': {('user_info', 'round')},
            },
        ),
    ]
