# Generated by Django 2.2.17 on 2023-10-02 11:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundinfo',
            name='round_number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
