# Generated by Django 2.2.17 on 2023-10-08 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorinfo',
            name='bidding_amount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
