# Generated by Django 2.2.17 on 2023-10-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0002_roundinfo_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundinfo',
            name='testing_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roundinfo',
            name='training_points',
            field=models.TextField(blank=True, null=True),
        ),
    ]
