# Generated by Django 2.2.17 on 2023-10-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0002_errorinfo_roundinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arithmetica.UserInfo'),
        ),
    ]
