# Generated by Django 2.2.17 on 2023-10-01 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0004_auto_20231002_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorinfo',
            name='credits',
            field=models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
