# Generated by Django 2.2.17 on 2023-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arithmetica', '0005_errorinfo_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='errorinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
